Actualización página principal idioma Español
BulzyKrown/Karu pull request #1
Opened 2021-01-19 13:03 UTC by TheEdaL06

[¡¡Inviten a Karu!!](https://discord.com/oauth2/authorize?client_id=413909677252935680&permissions=321600&redirect_uri=https%3A%2F%2Fdiscord.gg%2FSYYBU2F&response_type=code&scope=bot)

[Servidor de soporte](https://discord.com/invite/karu)

**[COÐΣ THΣΣÐAL ツᴮᴼᵀ#8126](https://portalmybot.com/u/theedal)**

2021-01-19 13:11 UTC, BulzyKrown requested changes
{:target="_blank"} se utiliza basicamente para que lo abra en una ventana nueva.

2021-01-19 13:11 UTC, BulzyKrown commented on lang/en/index.md
> -This parameter means that Karu can also search for the person, user or member you want by means of their ID, it is an optional form to not mention that person. If you want to know more about IDS visi
{:target="_blank"} remove? lul

2021-01-19 13:18 UTC, BulzyKrown requested changes
Revisa las lineas solicitadas, creo que hay ligeros cambios que pueden afectar

2021-01-19 13:18 UTC, BulzyKrown commented on lang/es/index.md
> +<p style="text-align: center;"><a href="https://bulzykrown.github.io/Karu/lang/en/"> English</a> | Español (Actualmente)</p>
Español (Actualmente) | Ingles

2021-01-19 13:18 UTC, BulzyKrown commented on lang/es/index.md
> +> Hola! Mi nombre es Karu n.n. Tengo 16 años y vengo aquí para ayudar a las comunidades a compartir experiencias únicas y divertidas. Puedo ayudarte a interactuar con otras personas, darles abrazos,
19 años owo

2021-01-19 13:18 UTC, BulzyKrown commented on lang/es/index.md
> -Este parametro significa que Karu tambien puede buscar a la persona, usuario o miembro que quieres por medio de su ID, es una forma opcional para no mencionar a esa persona. Si quieres saber más sobr
{:target="_blank"} :(

2021-02-18 20:11 UTC, TheEdaL06 reviewed
Karu! Let's Go

2021-02-19 17:56 UTC, BulzyKrown approved these changes

2021-02-19 17:57 UTC, merged